### ISSUE TITLE
Machete.split_list() throws an error on attempted use

### ISSUE THREAD

**Issue by JeffreyYStewart** [scottkleinman/lexos#16]
When I try to use Machete.split_list() I get the error `AttributeError: 'Machete' object has no attribute '_chunk_doc'`
The error is thrown on line 460 of cutter.__init__.py

**Comment by scottkleinman** [comment]
Since Cutter has been refactored in [https://github.com/scottkleinman/lexos/commit/127d810cdb1107ed25dcfb809dd7edf7b343cc1a](https://github.com/scottkleinman/lexos/commit/127d810cdb1107ed25dcfb809dd7edf7b343cc1a), I think this issue can be closed. Further problems can be handled in a separate issue.
